version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "3001:3000" # Maps container port 3000 to localhost:3001
    container_name: backend_container

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Maps container port 3000 to localhost:3000
    container_name: frontend_container
