services:
  backend:
    build: ./backend
    ports:
      - "3001:3000" # Maps container port 3000 to localhost:3001
    container_name: backend_container

  frontend:
    build: ./frontend
    ports:
      - "3000:3000" # Maps container port 3000 to localhost:3000
    container_name: frontend_container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minecraft_hosting
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80" # Access phpMyAdmin on localhost:8080
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
